sudo: required

services:
  - docker

before_install:
  - docker build -t dgp6182/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dgp6182/react-test npm test -- --coverage

after_success:
  - docker build -t dgp6182/multi-client ./client
  - docker build -t dgp6182/multi-server ./server
  - docker build -t dgp6182/multi-nginx  ./nginx
  - docker build -t dgp6182/multi-worker ./worker
  # Docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push the images to Dockerhub
  - docker push dgp6182/multi-client
  - docker push dgp6182/multi-nginx
  - docker push dgp6182/multi-server
  - docker push dgp6182/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-443515674418
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY